from tkinter import *

root = Tk()
root.title("Instructions")
l1 = Label(root , text="Instructions for MineSweeper")
l1.grid(row=0 , sticky=W)
l2 = Label(root , text="	Quick Start:")
l3 = Label(root , text="	- You are presented with a board of squares. Some squares contain mines (bombs), others don't. If you click on a square containing a bomb, you lose. If you manage to click all the squares (without clicking on any bombs) you win.")
l4 = Label(root , text="	- Clicking a square which doesn't have a bomb reveals the number of neighbouring squares containing bombs. Use this information plus some guess work to avoid the bombs.")
l5 = Label(root , text="	- To open a square, point at the square and click on it. To mark a square you think is a bomb, point and right-click (or hover with the mouse and press Space).")
l6 = Label(root , text="	Detailed Instructions:")
l7 = Label(root , text="	- A squares neighbours are the squares adjacent above, below, left, right, and all 4 diagonals. Squares on the sides of the board or in a corner have fewer neighbors. The board does not wrap around the edges.")
l8 = Label(root , text="	- If you open a square with 0 neighboring bombs, all its neighbors will automatically open. This can cause a large area to automatically open.")
l9 = Label(root , text="	- To remove a bomb marker from a square, point at it and right-click again.")
l10 = Label(root , text="	- The first square you open is never a bomb.")
l11 = Label(root , text="	- If you mark a bomb incorrectly, you will have to correct the mistake before you can win. Incorrect bomb marking doesn't kill you, but it can lead to mistakes which do.")
l12 = Label(root , text="	- You don't have to mark all the bombs to win; you just need to open all non-bomb squares.")
l13 = Label(root , text="	- Right-clicking twice will give you a question mark symbol which can be useful if you are unsure about a square . Click the yellow happy face to start a new game.")
l14 = Label(root , text="	Status Information:")
l15 = Label(root , text="	- The upper left corner contains the number of bombs left to find. The number will update as you mark and unmark squares.")
ll = Label(root , text="	- The upper right corner contains a time counter. The timer will max out at 999 (16 minutes 39 seconds).")
l16 = Label(root , text="	- Click on the time to switch to the number of moves counter. Click again to switch back to the time.")
l17 = Label(root , text="	Options and Enhancements:")
l18 = Label(root , text="	- Learning Mode - Show the contents of all unopened cells. Scores do not count towards high scores, and the Opening Move option does not apply.")
l19 = Label(root , text="	- Opening Move - Not only will the first square never be a bomb, but neither will any of the neighbors.")
l20 = Label(root , text=" 	- Marks (?) - Right clicking on a marked bomb will change the flag into a question mark. Right clicking again will change it back into an unmarked square.")
ll1 = Label(root , text="	- Area Open - If an open square has the correct number of marked neighboring bombs, click on the open square to open all remaining unopened neighbor squares all at once. ")
a = Label(root, text="	  If an incorrect number of neighbors are marked, or all neighbors are marked or open, clicking the square has no effect. If an incorrect neighbor is marked, this will cause instant death.")
l21 = Label(root , text="	- Open Remaining - Once the correct number of bombs have been marked, the bomb counter will turn blue. Click on the blue bomb counter to open all remaining cells. If any bombs are incorrectly marked, this will cause instant death.")
l2.grid(row=1 , sticky=W)
l3.grid(row=2 , sticky=W)
l4.grid(row=3 , sticky=W)
l5.grid(row=4 , sticky=W)
l6.grid(row=5 , sticky=W)
l7.grid(row=6 , sticky=W)
l8.grid(row=7 , sticky=W)
l9.grid(row=8 , sticky=W)
l10.grid(row=9 , sticky=W)
l11.grid(row=10 , sticky=W)
l12.grid(row=11 , sticky=W)
l13.grid(row=12 , sticky=W)
l14.grid(row=13 , sticky=W)
l15.grid(row=14 , sticky=W)
l16.grid(row=16 , sticky=W)
l17.grid(row=17 , sticky=W)
l18.grid(row=18 , sticky=W)
l19.grid(row=19 , sticky=W)
l20.grid(row=20 , sticky=W)
l21.grid(row=23 , sticky=W)
ll.grid(row=15 , sticky=W)
ll1.grid(row=21 , sticky=W)
a.grid(row=22 , sticky=W)

bu = Button(root , text="Close" , command=root.quit)
bu.grid(row=24)
root.mainloop()